[build]
builder = "NIXPACKS"
buildCommand = "npm run build --workspace=editor"

[deploy]
startCommand = "npm run start --workspace=editor"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
