[build]
builder = "NIXPACKS"
buildCommand = "npx turbo run build --filter=editor..."

[deploy]
startCommand = "cd apps/editor && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
