[build]
builder = "NIXPACKS"
buildCommand = "npx turbo run build --filter=interview..."

[deploy]
startCommand = "cd apps/interview && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
