[build]
builder = "NIXPACKS"
buildCommand = "npx turbo run build --filter=admin..."

[deploy]
startCommand = "cd apps/admin && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
